steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/conqueror:$SHORT_SHA',
        './server'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/conqueror:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'conqueror',
        '--image', 'gcr.io/$PROJECT_ID/conqueror:$SHORT_SHA',
        '--region', 'eu-west1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--set-secrets', 'API_KEY=conqueror-api-key:latest',
        '--set-env-vars', 'ENVIRONMENT=cloud',
      ]

images:
  - 'gcr.io/$PROJECT_ID/conqueror:$SHORT_SHA'
