steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/conqueror:$SHORT_SHA',
        './server'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/conqueror:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
        [
          'run', 'deploy', 'conqueror',
          '--image', 'gcr.io/$PROJECT_ID/conqueror:$SHORT_SHA',
          '--region', 'eu-west1',
          '--platform', 'managed',
          '--allow-unauthenticated',
          '--set-env-vars', 'API_KEY=$$SECRET_API_KEY',
      ]
    secretEnv:
      - 'SECRET_API_KEY'

images:
  - 'gcr.io/$PROJECT_ID/conqueror:$SHORT_SHA'

availableSecrets:
  secretManager:
  - versionName: projects/noted-cider-447509-b4/secrets/conqueror-api-key/versions/latest
    env: 'SECRET_API_KEY'