steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/conquerorv2:$SHORT_SHA',
        './server'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/conquerorv2:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
        [
          'run', 'deploy', 'conquerorv2',
          '--image', 'gcr.io/$PROJECT_ID/conqueror:$SHORT_SHA',
          '--region', 'eu-west1',
          '--platform', 'managed',
          '--allow-unauthenticated',
          '--set-env-vars', 'ENVIRONMENT=cloud',
          '--set-secrets', 'API_KEY=conqueror-api-key:latest',
      ]

images:
  - 'gcr.io/$PROJECT_ID/conquerorv2:$SHORT_SHA'
