steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/conqueror:$SHORT_SHA',
        './server'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/conqueror:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i "s|gcr.io/\$PROJECT_ID/conqueror:\$SHORT_SHA|gcr.io/$PROJECT_ID/conqueror:$SHORT_SHA|g" knative.yaml

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'services', 'replace', 'knative.yaml',
      '--region', 'eu-west1',
      '--platform', 'managed'
    ]

images:
  - 'gcr.io/$PROJECT_ID/conqueror:$SHORT_SHA'
