PRODUCTION_BUILDING_CAPACITY = 0

FARM_PRODUCTION_RATE = 0
FARM_CONSUMPTION_RATE = 0

WOODCUTTER_PRODUCTION_RATE = 0
WOODCUTTER_CONSUMPTION_RATE = 0

MINE_PRODUCTION_RATE = 0
MINE_CONSUMPTION_RATE = 0

TILE_BUILDING_CAPACITY = 0

WEAK_BOT_COLOR = (255, 0, 0)
MEDIUM_BOT_COLOR = (255, 165, 0)
STRONG_BOT_COLOR = (0, 255, 0)

OBSTACLE_COLOR = (0, 0, 0)
OBSTACLE_FREQUENCY = 0.0

OCEAN_COLOR = (0, 128, 255)
OCEAN_WIDTH = 0

CAPITAL_HP = 0.0
CAPITAL_TREASURE = 0.0

ATTACK_MOVE_PER_TILE = 0.125

INITIAL_FOOD = 0
INITIAL_WOOD = 0
INITIAL_METAL = 0
